import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
    id: {
        // Dashboard
        'dashboard.welcome': 'Selamat Datang Kembali!',
        'dashboard.summary': 'Berikut adalah ringkasan aktivitas Anda hari ini',
        'dashboard.totalArsipUnit': 'Total Arsip Unit',
        'dashboard.totalArsipUnitDesc': 'Jumlah arsip unit terdaftar',
        'dashboard.totalBerkasArsip': 'Total Berkas Arsip',
        'dashboard.totalBerkasArsipDesc': 'Jumlah berkas arsip terdaftar',
        'dashboard.totalUsers': 'Total Pengguna',
        'dashboard.totalUsersDesc': 'Jumlah pengguna terdaftar',
        'dashboard.recentArsipUnit': 'Arsip Unit Terbaru',
        'dashboard.arsipNumber': 'Nomor Arsip',
        'dashboard.description': 'Uraian',
        'dashboard.year': 'Tahun',
        'dashboard.classification': 'Klasifikasi',
        'dashboard.verified': 'Terverifikasi',
        'dashboard.administrator': 'Administrator',
        'dashboard.recentUsers': 'Pengguna Terbaru',
        'dashboard.noUsers': 'Belum ada pengguna terdaftar',
        'dashboard.thisMonth': 'user bulan ini',
        'dashboard.emailVerified': 'Email terverifikasi',
        'dashboard.roleAdmin': 'Role admin',
        'dashboard.monthlyStats': 'Statistik Bulanan',
        'dashboard.thisMonthBtn': 'Bulan Ini',
        'dashboard.chartPlaceholder': 'Grafik akan ditampilkan di sini',
        'dashboard.justNow': 'Baru saja',
        'dashboard.minutesAgo': 'menit yang lalu',
        'dashboard.hoursAgo': 'jam yang lalu',
        'dashboard.daysAgo': 'hari yang lalu',
        
        // Auth
        'auth.loginTitle': 'Masuk ke akun Anda',
        'auth.loginDesc': 'Masukkan email dan kata sandi Anda untuk masuk',
        'auth.registerTitle': 'Buat akun baru',
        'auth.registerDesc': 'Masukkan detail Anda untuk membuat akun',
        'auth.login': 'Masuk',
        'auth.register': 'Daftar',
        'auth.email': 'Email',
        'auth.emailPlaceholder': 'Masukkan email Anda',
        'auth.password': 'Kata Sandi',
        'auth.passwordPlaceholder': 'Masukkan kata sandi Anda',
        'auth.confirmPassword': 'Konfirmasi Kata Sandi',
        'auth.confirmPasswordPlaceholder': 'Ulangi kata sandi Anda',
        'auth.rememberMe': 'Ingat saya',
        'auth.forgotPassword': 'Lupa kata sandi?',
        'auth.loggingIn': 'Masuk...',
        'auth.signingUp': 'Mendaftar...',
        'auth.noAccount': 'Belum punya akun?',
        'auth.haveAccount': 'Sudah punya akun?',
        'auth.loginHere': 'Masuk di sini',
        'auth.registerHere': 'Daftar di sini',
        'auth.fullName': 'Nama Lengkap',
        'auth.fullNamePlaceholder': 'Masukkan nama lengkap Anda',
        
        // User Management
        'users.title': 'Manajemen Pengguna',
        'users.addUser': 'Tambah Pengguna',
        'users.createUser': 'Tambah Pengguna Baru',
        'users.editUser': 'Edit Pengguna',
        'users.fillForm': 'Isi form di bawah untuk menambahkan pengguna baru',
        'users.updateInfo': 'Perbarui informasi pengguna',
        'users.search': 'Cari pengguna...',
        'users.searchPlaceholder': 'Cari nama atau email...',
        'users.showEntries': 'Tampilkan',
        'users.entries': 'data',
        'users.filter': 'Filter',
        'users.allStatus': 'Semua Status',
        'users.verified': 'Terverifikasi',
        'users.unverified': 'Belum Verifikasi',
        'users.no': 'No',
        'users.name': 'Nama',
        'users.email': 'Email',
        'users.role': 'Role',
        'users.unitPengolah': 'Unit Pengolah',
        'users.selectUnitPengolah': 'Pilih Unit Pengolah',
        'users.allUnitPengolah': 'Semua Unit Pengolah',
        'users.status': 'Status',
        'users.registered': 'Terdaftar',
        'users.actions': 'Aksi',
        'users.noData': 'Tidak ada data pengguna',
        'users.verify': 'Verifikasi',
        'users.unverify': 'Batalkan Verifikasi',
        'users.edit': 'Edit',
        'users.delete': 'Hapus',
        'users.previous': 'Sebelumnya',
        'users.next': 'Selanjutnya',
        'users.showing': 'Menampilkan',
        'users.of': 'dari',
        'users.total': 'Total',
        'users.totalRegistered': 'pengguna terdaftar',
        'users.page': 'Halaman',
        'users.reset': 'Reset',
        'users.searchBtn': 'Cari',
        'users.admin': 'Admin',
        'users.management': 'Manajemen',
        'users.operator': 'Operator',
        'users.user': 'User',
        'users.deleteTitle': 'Konfirmasi Hapus Pengguna',
        'users.deleteMessage': 'Apakah Anda yakin ingin menghapus pengguna',
        'users.deleteWarning': 'Tindakan ini tidak dapat dibatalkan.',
        'users.deleting': 'Menghapus...',
        'users.verifyTitle': 'Verifikasi Email Pengguna',
        'users.unverifyTitle': 'Batalkan Verifikasi Email',
        'users.verifyMessage': 'Apakah Anda yakin ingin memverifikasi email pengguna',
        'users.verifyNote': 'Pengguna akan ditandai sebagai terverifikasi.',
        'users.unverifyMessage': 'Apakah Anda yakin ingin membatalkan verifikasi email pengguna',
        'users.unverifyNote': 'Pengguna akan ditandai sebagai belum terverifikasi.',
        'users.processing': 'Memproses...',
        
        // User Form
        'users.form.fullName': 'Nama Lengkap',
        'users.form.enterName': 'Masukkan nama lengkap',
        'users.form.password': 'Password',
        'users.form.minChars': 'Minimal 8 karakter',
        'users.form.confirmPassword': 'Konfirmasi Password',
        'users.form.repeatPassword': 'Ulangi password',
        'users.form.newPassword': 'Password Baru',
        'users.form.leaveEmpty': 'Kosongkan jika tidak ingin mengubah',
        'users.form.confirmNewPassword': 'Konfirmasi Password Baru',
        'users.form.repeatNewPassword': 'Ulangi password baru',
        'users.form.minCharsNote': 'Minimal 8 karakter jika ingin mengubah password',
        'users.form.userInfo': 'Informasi Pengguna',
        'users.form.emailVerified': '✓ Email Terverifikasi',
        'users.form.notVerified': '⚠ Belum Verifikasi',
        'users.form.registeredOn': 'Terdaftar:',
        'users.form.roleUser': 'User',
        'users.form.roleAdmin': 'Admin',
        'users.form.roleDescription': 'User: Akses terbatas | Admin: Akses penuh',
        'users.form.saving': 'Menyimpan...',
        'users.form.saveUser': 'Simpan Pengguna',
        'users.form.saveChanges': 'Simpan Perubahan',
        'users.form.cancel': 'Batal',
        'users.form.back': 'Kembali',
        
        // Profile
        'profile.title': 'Profil Saya',
        'profile.editProfile': 'Edit Profil',
        'profile.updateInfo': 'Perbarui nama dan alamat email Anda',
        'profile.manageProfile': 'Kelola informasi profil dan foto Anda',
        'profile.personalInfo': 'Informasi Pribadi',
        'profile.avatar': 'Foto Profil',
        'profile.changePhoto': 'Ubah Foto',
        'profile.removePhoto': 'Hapus Foto',
        'profile.maxSize': 'JPG, PNG, atau GIF (Max. 2MB)',
        'profile.confirmDelete': 'Apakah Anda yakin ingin menghapus foto profil?',
        'profile.accountInfo': 'Informasi Akun',
        'profile.security': 'Keamanan',
        'profile.changePassword': 'Ubah Password',
        'profile.changePasswordOptional': 'Ubah Password (Opsional)',
        'profile.currentPassword': 'Password Saat Ini',
        'profile.enterCurrentPassword': 'Masukkan password saat ini',
        'profile.leaveEmpty': 'Kosongkan jika tidak ingin mengubah password',
        'profile.emailUnverified': 'Alamat email Anda belum diverifikasi.',
        'profile.resendVerification': 'Klik di sini untuk mengirim ulang email verifikasi.',
        'profile.verificationSent': 'Link verifikasi baru telah dikirim ke alamat email Anda.',
        'profile.saved': 'Tersimpan',
        
        // Settings
        'settings.title': 'Pengaturan',
        'settings.description': 'Kelola profil dan pengaturan akun Anda',
        'settings.twoFactor': 'Autentikasi Dua Faktor',
        'settings.appearance': 'Tampilan',
        
        // Common
        'common.logout': 'Keluar',
        'common.loading': 'Memuat...',
        'common.save': 'Simpan',
        'common.saving': 'Menyimpan...',
        'common.cancel': 'Batal',
        'common.delete': 'Hapus',
        'common.edit': 'Edit',
        'common.close': 'Tutup',
        'common.confirm': 'Konfirmasi',
        'common.yes': 'Ya',
        'common.no': 'Tidak',
        'common.back': 'Kembali',
        'common.search': 'Cari',
        'common.reset': 'Reset',
        'common.select': 'Pilih',
        'common.update': 'Perbarui',
        'common.updating': 'Memperbarui...',
        'common.metadata': 'Metadata',
        'common.createdAt': 'Dibuat',
        'common.updatedAt': 'Terakhir Diupdate',
        'common.print': 'Cetak',
        
        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.userManagement': 'Manajemen Pengguna',
        'nav.master': 'Master',
        'nav.kodeKlasifikasi': 'Kode Klasifikasi',
        'nav.unitPengolah': 'Unit Pengolah',
        'nav.kategori': 'Kategori',
        'nav.subKategori': 'Sub Kategori',
        'nav.arsipUnit': 'Arsip Unit',
        'nav.berkasArsip': 'Berkas Arsip',
        'nav.laporan': 'Laporan',
        'nav.rekapUnitPengolah': 'Rekap per Unit Pengolah',
        'nav.penyusutan': 'Arsip Mendekati Penyusutan',
        'nav.statusVerifikasi': 'Status & Verifikasi Arsip',
        'nav.beritaAcaraPenyerahan': 'Berita Acara Penyerahan',
        'nav.repository': 'Repositori',
        'nav.documentation': 'Dokumentasi',

        // Kode Klasifikasi
        'kodeKlasifikasi.title': 'Kode Klasifikasi',
        'kodeKlasifikasi.add': 'Tambah Kode Klasifikasi',
        'kodeKlasifikasi.create': 'Tambah Kode Klasifikasi Baru',
        'kodeKlasifikasi.edit': 'Edit Kode Klasifikasi',
        'kodeKlasifikasi.fillForm': 'Isi form di bawah untuk menambahkan kode klasifikasi baru',
        'kodeKlasifikasi.updateInfo': 'Perbarui informasi kode klasifikasi',
        'kodeKlasifikasi.search': 'Cari kode atau uraian...',
        'kodeKlasifikasi.noData': 'Tidak ada data kode klasifikasi',
        'kodeKlasifikasi.kode': 'Kode',
        'kodeKlasifikasi.uraian': 'Uraian',
        'kodeKlasifikasi.parent': 'Kode Induk',
        'kodeKlasifikasi.retensiAktif': 'Retensi Aktif',
        'kodeKlasifikasi.retensiInaktif': 'Retensi Inaktif',
        'kodeKlasifikasi.statusAkhir': 'Status Akhir',
        'kodeKlasifikasi.klasifikasiKeamanan': 'Klasifikasi Keamanan',
        'kodeKlasifikasi.selectParent': '-- Pilih Kode Induk --',
        'kodeKlasifikasi.none': 'Tidak Ada',
        'kodeKlasifikasi.musnah': 'Musnah',
        'kodeKlasifikasi.permanen': 'Permanen',
        'kodeKlasifikasi.dinilaiKembali': 'Dinilai Kembali',
        'kodeKlasifikasi.biasa': 'Biasa',
        'kodeKlasifikasi.rahasia': 'Rahasia',
        'kodeKlasifikasi.terbatas': 'Terbatas',
        'kodeKlasifikasi.year': 'Tahun',
        'kodeKlasifikasi.enterKode': 'Masukkan kode klasifikasi',
        'kodeKlasifikasi.enterUraian': 'Masukkan uraian',
        'kodeKlasifikasi.deleteTitle': 'Konfirmasi Hapus Kode Klasifikasi',
        'kodeKlasifikasi.deleteMessage': 'Apakah Anda yakin ingin menghapus kode klasifikasi',
        'kodeKlasifikasi.deleteWarning': 'Tindakan ini tidak dapat dibatalkan.',

        // Unit Pengolah
        'unitPengolah.title': 'Unit Pengolah',
        'unitPengolah.add': 'Tambah Unit Pengolah',
        'unitPengolah.create': 'Tambah Unit Pengolah Baru',
        'unitPengolah.edit': 'Edit Unit Pengolah',
        'unitPengolah.fillForm': 'Isi form di bawah untuk menambahkan unit pengolah baru',
        'unitPengolah.updateInfo': 'Perbarui informasi unit pengolah',
        'unitPengolah.search': 'Cari nama unit...',
        'unitPengolah.noData': 'Tidak ada data unit pengolah',
        'unitPengolah.namaUnit': 'Nama Unit',
        'unitPengolah.enterNamaUnit': 'Masukkan nama unit pengolah',
        'unitPengolah.deleteTitle': 'Konfirmasi Hapus Unit Pengolah',
        'unitPengolah.deleteMessage': 'Apakah Anda yakin ingin menghapus unit pengolah',
        'unitPengolah.deleteWarning': 'Tindakan ini tidak dapat dibatalkan.',

        // Kategori
        'kategori.title': 'Kategori',
        'kategori.add': 'Tambah Kategori',
        'kategori.create': 'Tambah Kategori Baru',
        'kategori.edit': 'Edit Kategori',
        'kategori.fillForm': 'Isi form di bawah untuk menambahkan kategori baru',
        'kategori.updateInfo': 'Perbarui informasi kategori',
        'kategori.search': 'Cari nama atau deskripsi...',
        'kategori.noData': 'Tidak ada data kategori',
        'kategori.namaKategori': 'Nama Kategori',
        'kategori.deskripsi': 'Deskripsi',
        'kategori.subKategoriCount': 'Jumlah Sub Kategori',
        'kategori.enterNamaKategori': 'Masukkan nama kategori',
        'kategori.enterDeskripsi': 'Masukkan deskripsi (opsional)',
        'kategori.deleteTitle': 'Konfirmasi Hapus Kategori',
        'kategori.deleteMessage': 'Apakah Anda yakin ingin menghapus kategori',
        'kategori.deleteWarning': 'Tindakan ini akan menghapus semua sub kategori yang terkait.',

        // Sub Kategori
        'subKategori.title': 'Sub Kategori',
        'subKategori.add': 'Tambah Sub Kategori',
        'subKategori.create': 'Tambah Sub Kategori Baru',
        'subKategori.edit': 'Edit Sub Kategori',
        'subKategori.fillForm': 'Isi form di bawah untuk menambahkan sub kategori baru',
        'subKategori.updateInfo': 'Perbarui informasi sub kategori',
        'subKategori.search': 'Cari nama atau deskripsi...',
        'subKategori.noData': 'Tidak ada data sub kategori',
        'subKategori.kategori': 'Kategori',
        'subKategori.namaSubKategori': 'Nama Sub Kategori',
        'subKategori.deskripsi': 'Deskripsi',
        'subKategori.selectKategori': '-- Pilih Kategori --',
        'subKategori.filterKategori': 'Filter Kategori',
        'subKategori.allKategori': 'Semua Kategori',
        'subKategori.enterNamaSubKategori': 'Masukkan nama sub kategori',
        'subKategori.enterDeskripsi': 'Masukkan deskripsi (opsional)',
        'subKategori.deleteTitle': 'Konfirmasi Hapus Sub Kategori',
        'subKategori.deleteMessage': 'Apakah Anda yakin ingin menghapus sub kategori',
        'subKategori.deleteWarning': 'Tindakan ini tidak dapat dibatalkan.',

        // Arsip Unit
        'arsipUnit.title': 'Arsip Unit',
        'arsipUnit.add': 'Tambah Arsip Unit',
        'arsipUnit.create': 'Tambah Arsip Unit Baru',
        'arsipUnit.edit': 'Edit Arsip Unit',
        'arsipUnit.view': 'Detail Arsip Unit',
        'arsipUnit.createDescription': 'Isi form di bawah untuk menambahkan arsip unit baru',
        'arsipUnit.editDescription': 'Perbarui informasi arsip unit',
        'arsipUnit.fillForm': 'Isi form di bawah untuk menambahkan arsip unit baru',
        'arsipUnit.updateInfo': 'Perbarui informasi arsip unit',
        'arsipUnit.search': 'Cari no item, uraian, atau indeks...',
        'arsipUnit.noData': 'Tidak ada data arsip unit',
        'arsipUnit.noItemArsip': 'No. Item Arsip',
        'arsipUnit.kodeKlasifikasi': 'Kode Klasifikasi',
        'arsipUnit.unitPengolah': 'Unit Pengolah',
        'arsipUnit.berkasArsip': 'Berkas Arsip',
        'arsipUnit.kategori': 'Kategori',
        'arsipUnit.subKategori': 'Sub Kategori',
        'arsipUnit.status': 'Status',
        'arsipUnit.publishStatus': 'Status Publikasi',
        'arsipUnit.tanggal': 'Tanggal',
        'arsipUnit.jumlah': 'Jumlah',
        'arsipUnit.indeks': 'Indeks',
        'arsipUnit.uraianInformasi': 'Uraian Informasi',
        'arsipUnit.retensiAktif': 'Retensi Aktif',
        'arsipUnit.retensiInaktif': 'Retensi Inaktif',
        'arsipUnit.tingkatPerkembangan': 'Tingkat Perkembangan',
        'arsipUnit.skkaad': 'SKKAAD',
        'arsipUnit.lokasi': 'Lokasi',
        'arsipUnit.ruangan': 'Ruangan',
        'arsipUnit.noFilling': 'No. Filling',
        'arsipUnit.noLaci': 'No. Laci',
        'arsipUnit.noFolder': 'No. Folder',
        'arsipUnit.noBox': 'No. Box',
        'arsipUnit.dokumen': 'Dokumen',
        'arsipUnit.keterangan': 'Keterangan',
        'arsipUnit.jumlahNilai': 'Jumlah Nilai',
        'arsipUnit.jumlahSatuan': 'Jumlah Satuan',
        'arsipUnit.verifikasi': 'Verifikasi',
        'arsipUnit.verifiedBy': 'Diverifikasi Oleh',
        'arsipUnit.verifiedAt': 'Tanggal Verifikasi',
        'arsipUnit.verificationNotes': 'Catatan Verifikasi',
        'arsipUnit.submittedAt': 'Tanggal Pengajuan',
        'arsipUnit.verifikasiOleh': 'Verifikasi Oleh',
        'arsipUnit.verifikasiTanggal': 'Tanggal Verifikasi',
        'arsipUnit.verifikasiKeterangan': 'Keterangan Verifikasi',
        'arsipUnit.selectKodeKlasifikasi': '-- Pilih Kode Klasifikasi --',
        'arsipUnit.selectUnitPengolah': '-- Pilih Unit Pengolah --',
        'arsipUnit.selectBerkasArsip': '-- Pilih Berkas Arsip --',
        'arsipUnit.selectKategori': '-- Pilih Kategori --',
        'arsipUnit.selectSubKategori': '-- Pilih Sub Kategori --',
        'arsipUnit.filterStatus': 'Filter Status',
        'arsipUnit.filterPublishStatus': 'Filter Status Publikasi',
        'arsipUnit.allStatus': 'Semua Status',
        'arsipUnit.allPublishStatus': 'Semua Status Publikasi',
        'arsipUnit.pending': 'Menunggu',
        'arsipUnit.diterima': 'Diterima',
        'arsipUnit.ditolak': 'Ditolak',
        'arsipUnit.draft': 'Draft',
        'arsipUnit.published': 'Dipublikasi',
        'arsipUnit.archived': 'Diarsipkan',
        'arsipUnit.year': 'Tahun',
        'arsipUnit.enterNoItemArsip': 'Masukkan nomor item arsip',
        'arsipUnit.enterIndeks': 'Masukkan indeks',
        'arsipUnit.enterUraianInformasi': 'Masukkan uraian informasi',
        'arsipUnit.enterJumlahNilai': 'Masukkan jumlah nilai',
        'arsipUnit.enterJumlahSatuan': 'Masukkan satuan (misal: Berkas, Dokumen, dll)',
        'arsipUnit.enterTingkatPerkembangan': 'Masukkan tingkat perkembangan',
        'arsipUnit.enterSKKAAD': 'Masukkan SKKAAD',
        'arsipUnit.enterRuangan': 'Masukkan ruangan',
        'arsipUnit.enterNoFilling': 'Masukkan nomor filling',
        'arsipUnit.enterNoLaci': 'Masukkan nomor laci',
        'arsipUnit.enterNoFolder': 'Masukkan nomor folder',
        'arsipUnit.enterNoBox': 'Masukkan nomor box',
        'arsipUnit.enterDokumen': 'Masukkan dokumen',
        'arsipUnit.enterKeterangan': 'Masukkan keterangan (opsional)',
        'arsipUnit.deleteTitle': 'Konfirmasi Hapus Arsip Unit',
        'arsipUnit.deleteMessage': 'Apakah Anda yakin ingin menghapus arsip unit',
        'arsipUnit.deleteWarning': 'Tindakan ini tidak dapat dibatalkan.',
        'arsipUnit.informasiUmum': 'Informasi Umum',

        // Berkas Arsip
        'berkasArsip.title': 'Berkas Arsip',
        'berkasArsip.description': 'Kelola berkas arsip dan dokumentasi',
        'berkasArsip.add': 'Tambah Berkas Arsip',
        'berkasArsip.create': 'Tambah Berkas Arsip Baru',
        'berkasArsip.edit': 'Edit Berkas Arsip',
        'berkasArsip.detail': 'Detail Berkas Arsip',
        'berkasArsip.view': 'Lihat Berkas Arsip',
        'berkasArsip.fillForm': 'Isi form di bawah untuk menambahkan berkas arsip baru',
        'berkasArsip.updateInfo': 'Perbarui informasi berkas arsip',
        'berkasArsip.search': 'Cari nama berkas atau lokasi...',
        'berkasArsip.noData': 'Tidak ada data berkas arsip',
        'berkasArsip.nomorBerkas': 'Nomor Berkas',
        'berkasArsip.namaBerkas': 'Nama Berkas',
        'berkasArsip.kodeKlasifikasi': 'Kode Klasifikasi',
        'berkasArsip.retensi': 'Retensi',
        'berkasArsip.retensiAktif': 'Retensi Aktif',
        'berkasArsip.retensiInaktif': 'Retensi Inaktif',
        'berkasArsip.penyusutanAkhir': 'Penyusutan Akhir',
        'berkasArsip.lokasiFisik': 'Lokasi Fisik',
        'berkasArsip.uraian': 'Uraian',
        'berkasArsip.jumlahArsip': 'Jumlah Arsip',
        'berkasArsip.selectKlasifikasi': '-- Pilih Kode Klasifikasi --',
        'berkasArsip.filterKlasifikasi': 'Filter Klasifikasi',
        'berkasArsip.allKlasifikasi': 'Semua Klasifikasi',
        'berkasArsip.enterNamaBerkas': 'Masukkan nama berkas',
        'berkasArsip.enterPenyusutanAkhir': 'Masukkan penyusutan akhir',
        'berkasArsip.enterLokasiFisik': 'Masukkan lokasi fisik',
        'berkasArsip.enterUraian': 'Masukkan uraian (opsional)',
        'berkasArsip.deleteTitle': 'Konfirmasi Hapus Berkas Arsip',
        'berkasArsip.deleteConfirmation': 'Apakah Anda yakin ingin menghapus berkas arsip ini? Tindakan ini tidak dapat dibatalkan.',
        'berkasArsip.informasiBerkas': 'Informasi Berkas',
        'berkasArsip.daftarArsipUnit': 'Daftar Arsip Unit',
        'berkasArsip.tahun': 'Tahun',

        'arsipUnit.informasiRetensi': 'Informasi Retensi',
        'arsipUnit.informasiLokasi': 'Informasi Lokasi',
        'arsipUnit.informasiVerifikasi': 'Informasi Verifikasi',
        'arsipUnit.detail': 'Detail Arsip Unit',
        'arsipUnit.downloadDokumen': 'Download Dokumen',
        'arsipUnit.informasiArsip': 'Informasi Arsip',
        'arsipUnit.lokasiPenyimpanan': 'Lokasi Penyimpanan & Detail',
        'arsipUnit.tahun': 'tahun',
        'arsipUnit.tidakAdaLokasiPenyimpanan': 'Tidak ada data lokasi penyimpanan',
        'arsipUnit.tanggalVerifikasi': 'Tanggal Verifikasi',
        'arsipUnit.diverifikasiOleh': 'Diverifikasi Oleh',

        // Laporan - Navigation & Common
        'laporan.title': 'Laporan',
        'laporan.dashboard': 'Dashboard',
        'laporan.generating': 'Generating...',
        'laporan.generatePdf': 'Generate Laporan PDF',
        'laporan.aboutReport': 'Tentang Laporan Ini',
        
        // Laporan Penyusutan
        'laporan.penyusutan.title': 'Laporan Arsip Mendekati Penyusutan',
        'laporan.penyusutan.breadcrumb': 'Arsip Mendekati Penyusutan',
        'laporan.penyusutan.description': 'Generate laporan arsip yang mendekati atau telah melewati masa retensi',
        'laporan.penyusutan.immediateDisposal': 'Segera Disusutkan',
        'laporan.penyusutan.immediateDisposalDesc': 'Arsip yang sudah melewati masa retensi dan perlu tindakan segera',
        'laporan.penyusutan.approachingDisposal': 'Mendekati Penyusutan',
        'laporan.penyusutan.approachingDisposalDesc': 'Arsip yang akan memasuki masa penyusutan dalam waktu dekat',
        'laporan.penyusutan.aboutDescription': 'Laporan ini menampilkan daftar arsip berdasarkan perhitungan masa retensi:',
        'laporan.penyusutan.activeRetention': 'Masa Retensi Aktif:',
        'laporan.penyusutan.activeRetentionDesc': 'Periode arsip disimpan di unit pengolah',
        'laporan.penyusutan.inactiveRetention': 'Masa Retensi Inaktif:',
        'laporan.penyusutan.inactiveRetentionDesc': 'Periode arsip disimpan di pusat arsip',
        'laporan.penyusutan.totalRetention': 'Total Retensi:',
        'laporan.penyusutan.totalRetentionDesc': 'Retensi Aktif + Retensi Inaktif',
        'laporan.penyusutan.disposalDate': 'Tanggal Penyusutan:',
        'laporan.penyusutan.disposalDateDesc': 'Tanggal arsip + Total Retensi',
        'laporan.penyusutan.finalStatus': 'Status Akhir Arsip:',
        'laporan.penyusutan.destroy': 'Musnah:',
        'laporan.penyusutan.destroyDesc': 'Arsip akan dimusnahkan setelah masa retensi',
        'laporan.penyusutan.permanent': 'Permanen:',
        'laporan.penyusutan.permanentDesc': 'Arsip disimpan secara permanen',
        'laporan.penyusutan.reEvaluate': 'Nilai Guna:',
        'laporan.penyusutan.reEvaluateDesc': 'Perlu dinilai ulang untuk menentukan penyusutan',
        'laporan.penyusutan.generateReport': 'Generate Laporan',
        'laporan.penyusutan.referenceYear': 'Tahun Acuan Perhitungan',
        'laporan.penyusutan.referenceYearDesc': 'Tahun yang digunakan sebagai acuan untuk menghitung sisa waktu retensi',
        'laporan.penyusutan.warningLimit': 'Batas Peringatan (Tahun)',
        'laporan.penyusutan.warningLimitDesc': 'Arsip dengan sisa waktu kurang dari batas ini akan ditampilkan sebagai "Mendekati Penyusutan"',
        'laporan.penyusutan.year1': '1 Tahun',
        'laporan.penyusutan.year2': '2 Tahun',
        'laporan.penyusutan.year3': '3 Tahun',
        'laporan.penyusutan.year5': '5 Tahun',
        'laporan.penyusutan.unitPengolah': 'Unit Pengolah',
        'laporan.penyusutan.allUnits': 'Semua Unit Pengolah',
        'laporan.penyusutan.filterByUnit': 'Filter arsip berdasarkan unit pengolah tertentu',

        // Laporan Status Verifikasi
        'laporan.statusVerifikasi.title': 'Laporan Status & Verifikasi Arsip',
        'laporan.statusVerifikasi.breadcrumb': 'Status & Verifikasi Arsip',
        'laporan.statusVerifikasi.description': 'Generate laporan arsip berdasarkan status dan informasi verifikasi',
        'laporan.statusVerifikasi.pending': 'Pending',
        'laporan.statusVerifikasi.pendingDesc': 'Menunggu verifikasi',
        'laporan.statusVerifikasi.accepted': 'Diterima',
        'laporan.statusVerifikasi.acceptedDesc': 'Sudah disetujui',
        'laporan.statusVerifikasi.rejected': 'Ditolak',
        'laporan.statusVerifikasi.rejectedDesc': 'Tidak disetujui',
        'laporan.statusVerifikasi.aboutDescription': 'Laporan ini menampilkan arsip unit berdasarkan status dan informasi verifikasi:',
        'laporan.statusVerifikasi.pendingInfo': 'Arsip yang menunggu proses verifikasi',
        'laporan.statusVerifikasi.acceptedInfo': 'Arsip yang sudah diverifikasi dan disetujui',
        'laporan.statusVerifikasi.rejectedInfo': 'Arsip yang tidak disetujui beserta alasan penolakannya',
        'laporan.statusVerifikasi.verificationInfo': 'Informasi Verifikasi:',
        'laporan.statusVerifikasi.verifierName': 'Nama verifikator yang memproses arsip',
        'laporan.statusVerifikasi.verificationDateTime': 'Tanggal dan waktu verifikasi',
        'laporan.statusVerifikasi.notes': 'Catatan atau alasan penolakan',
        'laporan.statusVerifikasi.publishStatus': 'Status publikasi arsip',
        'laporan.statusVerifikasi.filterStatus': 'Filter Status',
        'laporan.statusVerifikasi.allStatus': 'Semua Status',
        'laporan.statusVerifikasi.selectAllStatus': 'Pilih "Semua Status" untuk menampilkan arsip dengan semua status',
        'laporan.statusVerifikasi.fromDate': 'Dari Tanggal',
        'laporan.statusVerifikasi.toDate': 'Sampai Tanggal',

        // Laporan Berita Acara Penyerahan
        'laporan.beritaAcara.title': 'Berita Acara Penyerahan Arsip',
        'laporan.beritaAcara.breadcrumb': 'Berita Acara Penyerahan Arsip',
        'laporan.beritaAcara.description': 'Buat berita acara untuk serah terima arsip antar unit atau ke pihak eksternal',
        'laporan.beritaAcara.aboutTitle': 'Tentang Berita Acara',
        'laporan.beritaAcara.aboutDescription': 'Dokumen resmi yang mencatat serah terima arsip dari satu unit ke unit lain atau ke pihak eksternal.',
        'laporan.beritaAcara.handoverForm': 'Form Penyerahan',
        'laporan.beritaAcara.originUnit': 'Unit Pengolah Asal',
        'laporan.beritaAcara.selectOriginUnit': '-- Pilih Unit Asal --',
        'laporan.beritaAcara.originUnitRequired': 'Unit pengolah asal harus dipilih',
        'laporan.beritaAcara.externalRecipient': 'Penerima eksternal (bukan unit internal)',
        'laporan.beritaAcara.destinationUnit': 'Unit Pengolah Tujuan',
        'laporan.beritaAcara.selectDestinationUnit': '-- Pilih Unit Tujuan --',
        'laporan.beritaAcara.destinationUnitRequired': 'Unit pengolah tujuan harus dipilih',
        'laporan.beritaAcara.recipientName': 'Nama Penerima',
        'laporan.beritaAcara.recipientNamePlaceholder': 'Nama lengkap penerima',
        'laporan.beritaAcara.recipientNameRequired': 'Nama penerima harus diisi',
        'laporan.beritaAcara.recipientPosition': 'Jabatan Penerima',
        'laporan.beritaAcara.recipientPositionPlaceholder': 'Jabatan penerima (opsional)',
        'laporan.beritaAcara.handoverDate': 'Tanggal Penyerahan',
        'laporan.beritaAcara.handoverDateRequired': 'Tanggal penyerahan harus diisi',
        'laporan.beritaAcara.notes': 'Keterangan',
        'laporan.beritaAcara.notesPlaceholder': 'Catatan tambahan (opsional)',
        'laporan.beritaAcara.selectedArchives': 'Arsip dipilih:',
        'laporan.beritaAcara.item': 'item',
        'laporan.beritaAcara.selectMinArchive': 'Pilih minimal 1 arsip untuk diserahkan',
        'laporan.beritaAcara.createPdf': 'Buat Berita Acara PDF',
        'laporan.beritaAcara.selectArchives': 'Pilih Arsip untuk Diserahkan',
        'laporan.beritaAcara.selectAll': 'Pilih Semua',
        'laporan.beritaAcara.deselectAll': 'Batal Pilih',
        'laporan.beritaAcara.searchArchive': 'Cari arsip berdasarkan kode, nomor item, atau uraian...',
        'laporan.beritaAcara.selectOriginFirst': 'Pilih unit pengolah asal terlebih dahulu untuk memfilter arsip',
        'laporan.beritaAcara.noArchiveAvailable': 'Tidak ada arsip yang tersedia untuk unit ini',
        'laporan.beritaAcara.selectOriginToShow': 'Pilih unit pengolah asal untuk menampilkan arsip',
        'laporan.beritaAcara.showing': 'Menampilkan',
        'laporan.beritaAcara.archives': 'arsip',
        'laporan.beritaAcara.selected': 'dipilih',
        'laporan.beritaAcara.connectionError': 'Gagal terhubung ke server. Silakan coba lagi.',
        'laporan.beritaAcara.generateError': 'Terjadi kesalahan saat generate PDF. Silakan coba lagi.',

        // Laporan Rekap Unit Pengolah
        'laporan.rekapUnit.title': 'Laporan Rekap Arsip per Unit Pengolah',
        'laporan.rekapUnit.breadcrumb': 'Rekap per Unit Pengolah',
        'laporan.rekapUnit.description': 'Generate laporan statistik arsip berdasarkan unit pengolah',
        'laporan.rekapUnit.processingUnits': 'Unit Pengolah',
        'laporan.rekapUnit.archivePerUnit': 'Arsip',
        'laporan.rekapUnit.perUnit': 'Per Unit',
        'laporan.rekapUnit.statistics': 'Statistik',
        'laporan.rekapUnit.complete': 'Lengkap',
        'laporan.rekapUnit.proportion': 'Proporsi',
        'laporan.rekapUnit.visual': 'Visual',
        'laporan.rekapUnit.aboutDescription': 'Laporan ini memberikan ringkasan statistik arsip untuk setiap unit pengolah:',
        'laporan.rekapUnit.archiveCount': 'Jumlah Arsip:',
        'laporan.rekapUnit.archiveCountDesc': 'Total arsip unit yang dimiliki setiap unit pengolah',
        'laporan.rekapUnit.fileCount': 'Jumlah Berkas:',
        'laporan.rekapUnit.fileCountDesc': 'Total berkas arsip yang dimiliki setiap unit pengolah',
        'laporan.rekapUnit.verificationStatus': 'Status Verifikasi:',
        'laporan.rekapUnit.verificationStatusDesc': 'Breakdown arsip berdasarkan status (Pending, Diterima, Ditolak)',
        'laporan.rekapUnit.proportionInfo': 'Proporsi:',
        'laporan.rekapUnit.proportionInfoDesc': 'Visualisasi persentase kontribusi setiap unit terhadap total arsip',
        'laporan.rekapUnit.displayedInfo': 'Informasi yang Ditampilkan:',
        'laporan.rekapUnit.overallSummary': 'Ringkasan keseluruhan (total unit, arsip, berkas, rata-rata)',
        'laporan.rekapUnit.recapTable': 'Tabel rekap per unit pengolah dengan status verifikasi',
        'laporan.rekapUnit.barChart': 'Visualisasi proporsi dalam bentuk bar chart',
        'laporan.rekapUnit.verificationSummary': 'Ringkasan status verifikasi keseluruhan',
        'laporan.rekapUnit.unitList': 'Daftar Unit Pengolah',
        'laporan.rekapUnit.generateReport': 'Generate Laporan',
        'laporan.rekapUnit.tips': 'Tips:',
        'laporan.rekapUnit.tipsDesc': 'Laporan akan menampilkan rekap semua unit pengolah. Gunakan filter tanggal untuk membatasi periode data.',
        'laporan.rekapUnit.fromDate': 'Dari Tanggal',
        'laporan.rekapUnit.leaveEmptyFrom': 'Kosongkan untuk mengambil semua data',
        'laporan.rekapUnit.toDate': 'Sampai Tanggal',
        'laporan.rekapUnit.leaveEmptyTo': 'Kosongkan untuk mengambil sampai hari ini',
    },
    en: {
        // Dashboard
        'dashboard.welcome': 'Welcome Back!',
        'dashboard.summary': 'Here is your activity summary for today',
        'dashboard.totalArsipUnit': 'Total Unit Archives',
        'dashboard.totalArsipUnitDesc': 'Number of registered unit archives',
        'dashboard.totalBerkasArsip': 'Total Archive Files',
        'dashboard.totalBerkasArsipDesc': 'Number of registered archive files',
        'dashboard.totalUsers': 'Total Users',
        'dashboard.totalUsersDesc': 'Number of registered users',
        'dashboard.recentArsipUnit': 'Recent Unit Archives',
        'dashboard.arsipNumber': 'Archive Number',
        'dashboard.description': 'Description',
        'dashboard.year': 'Year',
        'dashboard.classification': 'Classification',
        'dashboard.verified': 'Verified',
        'dashboard.administrator': 'Administrator',
        'dashboard.recentUsers': 'Recent Users',
        'dashboard.noUsers': 'No users registered yet',
        'dashboard.thisMonth': 'users this month',
        'dashboard.emailVerified': 'Email verified',
        'dashboard.roleAdmin': 'Admin role',
        'dashboard.monthlyStats': 'Monthly Statistics',
        'dashboard.thisMonthBtn': 'This Month',
        'dashboard.chartPlaceholder': 'Chart will be displayed here',
        'dashboard.justNow': 'Just now',
        'dashboard.minutesAgo': 'minutes ago',
        'dashboard.hoursAgo': 'hours ago',
        'dashboard.daysAgo': 'days ago',
        
        // Auth
        'auth.loginTitle': 'Login to your account',
        'auth.loginDesc': 'Enter your email and password to login',
        'auth.registerTitle': 'Create new account',
        'auth.registerDesc': 'Enter your details to create an account',
        'auth.login': 'Login',
        'auth.register': 'Register',
        'auth.email': 'Email',
        'auth.emailPlaceholder': 'Enter your email',
        'auth.password': 'Password',
        'auth.passwordPlaceholder': 'Enter your password',
        'auth.confirmPassword': 'Confirm Password',
        'auth.confirmPasswordPlaceholder': 'Repeat your password',
        'auth.rememberMe': 'Remember me',
        'auth.forgotPassword': 'Forgot password?',
        'auth.loggingIn': 'Logging in...',
        'auth.signingUp': 'Signing up...',
        'auth.noAccount': 'Don\'t have an account?',
        'auth.haveAccount': 'Already have an account?',
        'auth.loginHere': 'Login here',
        'auth.registerHere': 'Register here',
        'auth.fullName': 'Full Name',
        'auth.fullNamePlaceholder': 'Enter your full name',
        
        // User Management
        'users.title': 'User Management',
        'users.addUser': 'Add User',
        'users.createUser': 'Create New User',
        'users.editUser': 'Edit User',
        'users.fillForm': 'Fill the form below to add a new user',
        'users.updateInfo': 'Update user information',
        'users.search': 'Search users...',
        'users.searchPlaceholder': 'Search name or email...',
        'users.showEntries': 'Show',
        'users.entries': 'entries',
        'users.filter': 'Filter',
        'users.allStatus': 'All Status',
        'users.verified': 'Verified',
        'users.unverified': 'Unverified',
        'users.no': 'No',
        'users.name': 'Name',
        'users.email': 'Email',
        'users.role': 'Role',
        'users.unitPengolah': 'Processing Unit',
        'users.selectUnitPengolah': 'Select Processing Unit',
        'users.allUnitPengolah': 'All Processing Unit',
        'users.status': 'Status',
        'users.registered': 'Registered',
        'users.actions': 'Actions',
        'users.noData': 'No user data',
        'users.verify': 'Verify',
        'users.unverify': 'Unverify',
        'users.edit': 'Edit',
        'users.delete': 'Delete',
        'users.previous': 'Previous',
        'users.next': 'Next',
        'users.showing': 'Showing',
        'users.of': 'of',
        'users.total': 'Total',
        'users.totalRegistered': 'registered users',
        'users.page': 'Page',
        'users.reset': 'Reset',
        'users.searchBtn': 'Search',
        'users.admin': 'Admin',
        'users.management': 'Management',
        'users.operator': 'Operator',
        'users.user': 'User',
        'users.deleteTitle': 'Confirm Delete User',
        'users.deleteMessage': 'Are you sure you want to delete user',
        'users.deleteWarning': 'This action cannot be undone.',
        'users.deleting': 'Deleting...',
        'users.verifyTitle': 'Verify User Email',
        'users.unverifyTitle': 'Unverify Email',
        'users.verifyMessage': 'Are you sure you want to verify email for user',
        'users.verifyNote': 'User will be marked as verified.',
        'users.unverifyMessage': 'Are you sure you want to unverify email for user',
        'users.unverifyNote': 'User will be marked as unverified.',
        'users.processing': 'Processing...',
        
        // User Form
        'users.form.fullName': 'Full Name',
        'users.form.enterName': 'Enter full name',
        'users.form.password': 'Password',
        'users.form.minChars': 'Minimum 8 characters',
        'users.form.confirmPassword': 'Confirm Password',
        'users.form.repeatPassword': 'Repeat password',
        'users.form.newPassword': 'New Password',
        'users.form.leaveEmpty': 'Leave empty if you don\'t want to change',
        'users.form.confirmNewPassword': 'Confirm New Password',
        'users.form.repeatNewPassword': 'Repeat new password',
        'users.form.minCharsNote': 'Minimum 8 characters if you want to change password',
        'users.form.userInfo': 'User Information',
        'users.form.emailVerified': '✓ Email Verified',
        'users.form.notVerified': '⚠ Not Verified',
        'users.form.registeredOn': 'Registered:',
        'users.form.roleUser': 'User',
        'users.form.roleAdmin': 'Admin',
        'users.form.roleDescription': 'User: Limited access | Admin: Full access',
        'users.form.saving': 'Saving...',
        'users.form.saveUser': 'Save User',
        'users.form.saveChanges': 'Save Changes',
        'users.form.cancel': 'Cancel',
        'users.form.back': 'Back',
        
        // Profile
        'profile.title': 'My Profile',
        'profile.editProfile': 'Edit Profile',
        'profile.updateInfo': 'Update your name and email address',
        'profile.manageProfile': 'Manage your profile information and photo',
        'profile.personalInfo': 'Personal Information',
        'profile.avatar': 'Profile Photo',
        'profile.changePhoto': 'Change Photo',
        'profile.removePhoto': 'Remove Photo',
        'profile.maxSize': 'JPG, PNG, or GIF (Max. 2MB)',
        'profile.confirmDelete': 'Are you sure you want to delete your profile photo?',
        'profile.accountInfo': 'Account Information',
        'profile.security': 'Security',
        'profile.changePassword': 'Change Password',
        'profile.changePasswordOptional': 'Change Password (Optional)',
        'profile.currentPassword': 'Current Password',
        'profile.enterCurrentPassword': 'Enter current password',
        'profile.leaveEmpty': 'Leave empty if you don\'t want to change password',
        'profile.emailUnverified': 'Your email address is unverified.',
        'profile.resendVerification': 'Click here to resend the verification email.',
        'profile.verificationSent': 'A new verification link has been sent to your email address.',
        'profile.saved': 'Saved',
        
        // Settings
        'settings.title': 'Settings',
        'settings.description': 'Manage your profile and account settings',
        'settings.twoFactor': 'Two-Factor Authentication',
        'settings.appearance': 'Appearance',
        
        // Common
        'common.logout': 'Logout',
        'common.loading': 'Loading...',
        'common.save': 'Save',
        'common.saving': 'Saving...',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.close': 'Close',
        'common.confirm': 'Confirm',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.back': 'Back',
        'common.search': 'Search',
        'common.reset': 'Reset',
        'common.select': 'Select',
        'common.update': 'Update',
        'common.updating': 'Updating...',
        'common.metadata': 'Metadata',
        'common.createdAt': 'Created',
        'common.updatedAt': 'Last Updated',
        'common.print': 'Print',
        
        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.userManagement': 'User Management',
        'nav.master': 'Master',
        'nav.kodeKlasifikasi': 'Classification Code',
        'nav.unitPengolah': 'Processing Unit',
        'nav.kategori': 'Category',
        'nav.subKategori': 'Sub Category',
        'nav.arsipUnit': 'Unit Archive',
        'nav.berkasArsip': 'Archive Files',
        'nav.laporan': 'Reports',
        'nav.rekapUnitPengolah': 'Recap per Processing Unit',
        'nav.penyusutan': 'Archives Approaching Disposal',
        'nav.statusVerifikasi': 'Status & Verification',
        'nav.beritaAcaraPenyerahan': 'Handover Report',
        'nav.repository': 'Repository',
        'nav.documentation': 'Documentation',

        // Kode Klasifikasi
        'kodeKlasifikasi.title': 'Classification Code',
        'kodeKlasifikasi.add': 'Add Classification Code',
        'kodeKlasifikasi.create': 'Create New Classification Code',
        'kodeKlasifikasi.edit': 'Edit Classification Code',
        'kodeKlasifikasi.fillForm': 'Fill the form below to add a new classification code',
        'kodeKlasifikasi.updateInfo': 'Update classification code information',
        'kodeKlasifikasi.search': 'Search code or description...',
        'kodeKlasifikasi.noData': 'No classification code data',
        'kodeKlasifikasi.kode': 'Code',
        'kodeKlasifikasi.uraian': 'Description',
        'kodeKlasifikasi.parent': 'Parent Code',
        'kodeKlasifikasi.retensiAktif': 'Active Retention',
        'kodeKlasifikasi.retensiInaktif': 'Inactive Retention',
        'kodeKlasifikasi.statusAkhir': 'Final Status',
        'kodeKlasifikasi.klasifikasiKeamanan': 'Security Classification',
        'kodeKlasifikasi.selectParent': '-- Select Parent Code --',
        'kodeKlasifikasi.none': 'None',
        'kodeKlasifikasi.musnah': 'Destroy',
        'kodeKlasifikasi.permanen': 'Permanent',
        'kodeKlasifikasi.dinilaiKembali': 'Re-evaluate',
        'kodeKlasifikasi.biasa': 'Normal',
        'kodeKlasifikasi.rahasia': 'Secret',
        'kodeKlasifikasi.terbatas': 'Restricted',
        'kodeKlasifikasi.year': 'Year',
        'kodeKlasifikasi.enterKode': 'Enter classification code',
        'kodeKlasifikasi.enterUraian': 'Enter description',
        'kodeKlasifikasi.deleteTitle': 'Confirm Delete Classification Code',
        'kodeKlasifikasi.deleteMessage': 'Are you sure you want to delete classification code',
        'kodeKlasifikasi.deleteWarning': 'This action cannot be undone.',

        // Unit Pengolah
        'unitPengolah.title': 'Processing Unit',
        'unitPengolah.add': 'Add Processing Unit',
        'unitPengolah.create': 'Create New Processing Unit',
        'unitPengolah.edit': 'Edit Processing Unit',
        'unitPengolah.fillForm': 'Fill the form below to add a new processing unit',
        'unitPengolah.updateInfo': 'Update processing unit information',
        'unitPengolah.search': 'Search unit name...',
        'unitPengolah.noData': 'No processing unit data',
        'unitPengolah.namaUnit': 'Unit Name',
        'unitPengolah.enterNamaUnit': 'Enter processing unit name',
        'unitPengolah.deleteTitle': 'Confirm Delete Processing Unit',
        'unitPengolah.deleteMessage': 'Are you sure you want to delete processing unit',
        'unitPengolah.deleteWarning': 'This action cannot be undone.',

        // Kategori
        'kategori.title': 'Category',
        'kategori.add': 'Add Category',
        'kategori.create': 'Create New Category',
        'kategori.edit': 'Edit Category',
        'kategori.fillForm': 'Fill the form below to add a new category',
        'kategori.updateInfo': 'Update category information',
        'kategori.search': 'Search name or description...',
        'kategori.noData': 'No category data',
        'kategori.namaKategori': 'Category Name',
        'kategori.deskripsi': 'Description',
        'kategori.subKategoriCount': 'Sub Category Count',
        'kategori.enterNamaKategori': 'Enter category name',
        'kategori.enterDeskripsi': 'Enter description (optional)',
        'kategori.deleteTitle': 'Confirm Delete Category',
        'kategori.deleteMessage': 'Are you sure you want to delete category',
        'kategori.deleteWarning': 'This action will delete all related sub categories.',

        // Sub Kategori
        'subKategori.title': 'Sub Category',
        'subKategori.add': 'Add Sub Category',
        'subKategori.create': 'Create New Sub Category',
        'subKategori.edit': 'Edit Sub Category',
        'subKategori.fillForm': 'Fill the form below to add a new sub category',
        'subKategori.updateInfo': 'Update sub category information',
        'subKategori.search': 'Search name or description...',
        'subKategori.noData': 'No sub category data',
        'subKategori.kategori': 'Category',
        'subKategori.namaSubKategori': 'Sub Category Name',
        'subKategori.deskripsi': 'Description',
        'subKategori.selectKategori': '-- Select Category --',
        'subKategori.filterKategori': 'Filter Category',
        'subKategori.allKategori': 'All Categories',
        'subKategori.enterNamaSubKategori': 'Enter sub category name',
        'subKategori.enterDeskripsi': 'Enter description (optional)',
        'subKategori.deleteTitle': 'Confirm Delete Sub Category',
        'subKategori.deleteMessage': 'Are you sure you want to delete sub category',
        'subKategori.deleteWarning': 'This action cannot be undone.',

        // Arsip Unit
        'arsipUnit.title': 'Unit Archive',
        'arsipUnit.add': 'Add Unit Archive',
        'arsipUnit.create': 'Create New Unit Archive',
        'arsipUnit.edit': 'Edit Unit Archive',
        'arsipUnit.view': 'Unit Archive Details',
        'arsipUnit.createDescription': 'Fill the form below to add a new unit archive',
        'arsipUnit.editDescription': 'Update unit archive information',
        'arsipUnit.fillForm': 'Fill the form below to add a new unit archive',
        'arsipUnit.updateInfo': 'Update unit archive information',
        'arsipUnit.search': 'Search item no, description, or index...',
        'arsipUnit.noData': 'No unit archive data',
        'arsipUnit.noItemArsip': 'Archive Item No.',
        'arsipUnit.kodeKlasifikasi': 'Classification Code',
        'arsipUnit.unitPengolah': 'Processing Unit',
        'arsipUnit.berkasArsip': 'Archive File',
        'arsipUnit.kategori': 'Category',
        'arsipUnit.subKategori': 'Sub Category',
        'arsipUnit.status': 'Status',
        'arsipUnit.publishStatus': 'Publish Status',
        'arsipUnit.tanggal': 'Date',
        'arsipUnit.jumlah': 'Quantity',
        'arsipUnit.indeks': 'Index',
        'arsipUnit.uraianInformasi': 'Information Description',
        'arsipUnit.retensiAktif': 'Active Retention',
        'arsipUnit.retensiInaktif': 'Inactive Retention',
        'arsipUnit.tingkatPerkembangan': 'Development Level',
        'arsipUnit.skkaad': 'SKKAAD',
        'arsipUnit.lokasi': 'Location',
        'arsipUnit.ruangan': 'Room',
        'arsipUnit.noFilling': 'Filling No.',
        'arsipUnit.noLaci': 'Drawer No.',
        'arsipUnit.noFolder': 'Folder No.',
        'arsipUnit.noBox': 'Box No.',
        'arsipUnit.dokumen': 'Document',
        'arsipUnit.keterangan': 'Notes',
        'arsipUnit.jumlahNilai': 'Quantity Value',
        'arsipUnit.jumlahSatuan': 'Quantity Unit',
        'arsipUnit.verifikasi': 'Verification',
        'arsipUnit.verifiedBy': 'Verified By',
        'arsipUnit.verifiedAt': 'Verification Date',
        'arsipUnit.verificationNotes': 'Verification Notes',
        'arsipUnit.submittedAt': 'Submitted Date',
        'arsipUnit.verifikasiOleh': 'Verified By',
        'arsipUnit.verifikasiTanggal': 'Verification Date',
        'arsipUnit.verifikasiKeterangan': 'Verification Notes',
        'arsipUnit.selectKodeKlasifikasi': '-- Select Classification Code --',
        'arsipUnit.selectUnitPengolah': '-- Select Processing Unit --',
        'arsipUnit.selectBerkasArsip': '-- Select Archive File --',
        'arsipUnit.selectKategori': '-- Select Category --',
        'arsipUnit.selectSubKategori': '-- Select Sub Category --',
        'arsipUnit.filterStatus': 'Filter Status',
        'arsipUnit.filterPublishStatus': 'Filter Publish Status',
        'arsipUnit.allStatus': 'All Status',
        'arsipUnit.allPublishStatus': 'All Publish Status',
        'arsipUnit.pending': 'Pending',
        'arsipUnit.diterima': 'Accepted',
        'arsipUnit.ditolak': 'Rejected',
        'arsipUnit.draft': 'Draft',
        'arsipUnit.published': 'Published',
        'arsipUnit.archived': 'Archived',
        'arsipUnit.year': 'Year',
        'arsipUnit.enterNoItemArsip': 'Enter archive item number',
        'arsipUnit.enterIndeks': 'Enter index',
        'arsipUnit.enterUraianInformasi': 'Enter information description',
        'arsipUnit.enterJumlahNilai': 'Enter quantity value',
        'arsipUnit.enterJumlahSatuan': 'Enter unit (e.g: File, Document, etc)',
        'arsipUnit.enterTingkatPerkembangan': 'Enter development level',
        'arsipUnit.enterSKKAAD': 'Enter SKKAAD',
        'arsipUnit.enterRuangan': 'Enter room',
        'arsipUnit.enterNoFilling': 'Enter filling number',
        'arsipUnit.enterNoLaci': 'Enter drawer number',
        'arsipUnit.enterNoFolder': 'Enter folder number',
        'arsipUnit.enterNoBox': 'Enter box number',
        'arsipUnit.enterDokumen': 'Enter document',
        'arsipUnit.enterKeterangan': 'Enter notes (optional)',
        'arsipUnit.deleteTitle': 'Confirm Delete Unit Archive',
        'arsipUnit.deleteMessage': 'Are you sure you want to delete unit archive',
        'arsipUnit.deleteWarning': 'This action cannot be undone.',
        'arsipUnit.informasiUmum': 'General Information',

        // Berkas Arsip
        'berkasArsip.title': 'Archive Files',
        'berkasArsip.description': 'Manage archive files and documentation',
        'berkasArsip.add': 'Add Archive File',
        'berkasArsip.create': 'Add New Archive File',
        'berkasArsip.edit': 'Edit Archive File',
        'berkasArsip.detail': 'Archive File Detail',
        'berkasArsip.view': 'View Archive File',
        'berkasArsip.fillForm': 'Fill the form below to add a new archive file',
        'berkasArsip.updateInfo': 'Update archive file information',
        'berkasArsip.search': 'Search file name or location...',
        'berkasArsip.noData': 'No archive file data',
        'berkasArsip.nomorBerkas': 'File Number',
        'berkasArsip.namaBerkas': 'File Name',
        'berkasArsip.kodeKlasifikasi': 'Classification Code',
        'berkasArsip.retensi': 'Retention',
        'berkasArsip.retensiAktif': 'Active Retention',
        'berkasArsip.retensiInaktif': 'Inactive Retention',
        'berkasArsip.penyusutanAkhir': 'Final Disposal',
        'berkasArsip.lokasiFisik': 'Physical Location',
        'berkasArsip.uraian': 'Description',
        'berkasArsip.jumlahArsip': 'Archive Count',
        'berkasArsip.selectKlasifikasi': '-- Select Classification Code --',
        'berkasArsip.filterKlasifikasi': 'Filter Classification',
        'berkasArsip.allKlasifikasi': 'All Classifications',
        'berkasArsip.enterNamaBerkas': 'Enter file name',
        'berkasArsip.enterPenyusutanAkhir': 'Enter final disposal',
        'berkasArsip.enterLokasiFisik': 'Enter physical location',
        'berkasArsip.enterUraian': 'Enter description (optional)',
        'berkasArsip.deleteTitle': 'Confirm Delete Archive File',
        'berkasArsip.deleteConfirmation': 'Are you sure you want to delete this archive file? This action cannot be undone.',
        'berkasArsip.informasiBerkas': 'File Information',
        'berkasArsip.daftarArsipUnit': 'Unit Archive List',
        'berkasArsip.tahun': 'Years',

        'arsipUnit.informasiRetensi': 'Retention Information',
        'arsipUnit.informasiLokasi': 'Location Information',
        'arsipUnit.informasiVerifikasi': 'Verification Information',
        'arsipUnit.detail': 'Unit Archive Detail',
        'arsipUnit.downloadDokumen': 'Download Document',
        'arsipUnit.informasiArsip': 'Archive Information',
        'arsipUnit.lokasiPenyimpanan': 'Storage Location & Details',
        'arsipUnit.tahun': 'years',
        'arsipUnit.tidakAdaLokasiPenyimpanan': 'No storage location data available',
        'arsipUnit.tanggalVerifikasi': 'Verification Date',
        'arsipUnit.diverifikasiOleh': 'Verified By',

        // Laporan - Navigation & Common
        'laporan.title': 'Reports',
        'laporan.dashboard': 'Dashboard',
        'laporan.generating': 'Generating...',
        'laporan.generatePdf': 'Generate PDF Report',
        'laporan.aboutReport': 'About This Report',
        
        // Laporan Penyusutan
        'laporan.penyusutan.title': 'Archives Approaching Disposal Report',
        'laporan.penyusutan.breadcrumb': 'Archives Approaching Disposal',
        'laporan.penyusutan.description': 'Generate report of archives approaching or past retention period',
        'laporan.penyusutan.immediateDisposal': 'Immediate Disposal',
        'laporan.penyusutan.immediateDisposalDesc': 'Archives past retention period requiring immediate action',
        'laporan.penyusutan.approachingDisposal': 'Approaching Disposal',
        'laporan.penyusutan.approachingDisposalDesc': 'Archives that will enter disposal period soon',
        'laporan.penyusutan.aboutDescription': 'This report displays archives based on retention period calculation:',
        'laporan.penyusutan.activeRetention': 'Active Retention:',
        'laporan.penyusutan.activeRetentionDesc': 'Period archives are stored in processing unit',
        'laporan.penyusutan.inactiveRetention': 'Inactive Retention:',
        'laporan.penyusutan.inactiveRetentionDesc': 'Period archives are stored in archive center',
        'laporan.penyusutan.totalRetention': 'Total Retention:',
        'laporan.penyusutan.totalRetentionDesc': 'Active Retention + Inactive Retention',
        'laporan.penyusutan.disposalDate': 'Disposal Date:',
        'laporan.penyusutan.disposalDateDesc': 'Archive Date + Total Retention',
        'laporan.penyusutan.finalStatus': 'Final Archive Status:',
        'laporan.penyusutan.destroy': 'Destroy:',
        'laporan.penyusutan.destroyDesc': 'Archive will be destroyed after retention period',
        'laporan.penyusutan.permanent': 'Permanent:',
        'laporan.penyusutan.permanentDesc': 'Archive is stored permanently',
        'laporan.penyusutan.reEvaluate': 'Re-evaluate:',
        'laporan.penyusutan.reEvaluateDesc': 'Needs re-evaluation to determine disposal',
        'laporan.penyusutan.generateReport': 'Generate Report',
        'laporan.penyusutan.referenceYear': 'Reference Year for Calculation',
        'laporan.penyusutan.referenceYearDesc': 'Year used as reference to calculate remaining retention time',
        'laporan.penyusutan.warningLimit': 'Warning Limit (Years)',
        'laporan.penyusutan.warningLimitDesc': 'Archives with remaining time less than this limit will be shown as "Approaching Disposal"',
        'laporan.penyusutan.year1': '1 Year',
        'laporan.penyusutan.year2': '2 Years',
        'laporan.penyusutan.year3': '3 Years',
        'laporan.penyusutan.year5': '5 Years',
        'laporan.penyusutan.unitPengolah': 'Processing Unit',
        'laporan.penyusutan.allUnits': 'All Processing Units',
        'laporan.penyusutan.filterByUnit': 'Filter archives by specific processing unit',

        // Laporan Status Verifikasi
        'laporan.statusVerifikasi.title': 'Archive Status & Verification Report',
        'laporan.statusVerifikasi.breadcrumb': 'Archive Status & Verification',
        'laporan.statusVerifikasi.description': 'Generate archive report based on status and verification information',
        'laporan.statusVerifikasi.pending': 'Pending',
        'laporan.statusVerifikasi.pendingDesc': 'Awaiting verification',
        'laporan.statusVerifikasi.accepted': 'Accepted',
        'laporan.statusVerifikasi.acceptedDesc': 'Already approved',
        'laporan.statusVerifikasi.rejected': 'Rejected',
        'laporan.statusVerifikasi.rejectedDesc': 'Not approved',
        'laporan.statusVerifikasi.aboutDescription': 'This report displays unit archives based on status and verification information:',
        'laporan.statusVerifikasi.pendingInfo': 'Archives awaiting verification process',
        'laporan.statusVerifikasi.acceptedInfo': 'Archives that have been verified and approved',
        'laporan.statusVerifikasi.rejectedInfo': 'Archives that are not approved with rejection reasons',
        'laporan.statusVerifikasi.verificationInfo': 'Verification Information:',
        'laporan.statusVerifikasi.verifierName': 'Name of verifier who processed the archive',
        'laporan.statusVerifikasi.verificationDateTime': 'Verification date and time',
        'laporan.statusVerifikasi.notes': 'Notes or rejection reasons',
        'laporan.statusVerifikasi.publishStatus': 'Archive publish status',
        'laporan.statusVerifikasi.filterStatus': 'Filter Status',
        'laporan.statusVerifikasi.allStatus': 'All Status',
        'laporan.statusVerifikasi.selectAllStatus': 'Select "All Status" to display archives with all statuses',
        'laporan.statusVerifikasi.fromDate': 'From Date',
        'laporan.statusVerifikasi.toDate': 'To Date',

        // Laporan Berita Acara Penyerahan
        'laporan.beritaAcara.title': 'Archive Handover Report',
        'laporan.beritaAcara.breadcrumb': 'Archive Handover Report',
        'laporan.beritaAcara.description': 'Create handover document for archive transfer between units or to external parties',
        'laporan.beritaAcara.aboutTitle': 'About Handover Report',
        'laporan.beritaAcara.aboutDescription': 'Official document recording archive handover from one unit to another or to external parties.',
        'laporan.beritaAcara.handoverForm': 'Handover Form',
        'laporan.beritaAcara.originUnit': 'Origin Processing Unit',
        'laporan.beritaAcara.selectOriginUnit': '-- Select Origin Unit --',
        'laporan.beritaAcara.originUnitRequired': 'Origin processing unit must be selected',
        'laporan.beritaAcara.externalRecipient': 'External recipient (not internal unit)',
        'laporan.beritaAcara.destinationUnit': 'Destination Processing Unit',
        'laporan.beritaAcara.selectDestinationUnit': '-- Select Destination Unit --',
        'laporan.beritaAcara.destinationUnitRequired': 'Destination processing unit must be selected',
        'laporan.beritaAcara.recipientName': 'Recipient Name',
        'laporan.beritaAcara.recipientNamePlaceholder': 'Full recipient name',
        'laporan.beritaAcara.recipientNameRequired': 'Recipient name must be filled',
        'laporan.beritaAcara.recipientPosition': 'Recipient Position',
        'laporan.beritaAcara.recipientPositionPlaceholder': 'Recipient position (optional)',
        'laporan.beritaAcara.handoverDate': 'Handover Date',
        'laporan.beritaAcara.handoverDateRequired': 'Handover date must be filled',
        'laporan.beritaAcara.notes': 'Notes',
        'laporan.beritaAcara.notesPlaceholder': 'Additional notes (optional)',
        'laporan.beritaAcara.selectedArchives': 'Selected archives:',
        'laporan.beritaAcara.item': 'item',
        'laporan.beritaAcara.selectMinArchive': 'Select at least 1 archive to transfer',
        'laporan.beritaAcara.createPdf': 'Create Handover Report PDF',
        'laporan.beritaAcara.selectArchives': 'Select Archives to Transfer',
        'laporan.beritaAcara.selectAll': 'Select All',
        'laporan.beritaAcara.deselectAll': 'Deselect',
        'laporan.beritaAcara.searchArchive': 'Search archive by code, item number, or description...',
        'laporan.beritaAcara.selectOriginFirst': 'Select origin processing unit first to filter archives',
        'laporan.beritaAcara.noArchiveAvailable': 'No archives available for this unit',
        'laporan.beritaAcara.selectOriginToShow': 'Select origin processing unit to display archives',
        'laporan.beritaAcara.showing': 'Showing',
        'laporan.beritaAcara.archives': 'archives',
        'laporan.beritaAcara.selected': 'selected',
        'laporan.beritaAcara.connectionError': 'Failed to connect to server. Please try again.',
        'laporan.beritaAcara.generateError': 'An error occurred while generating PDF. Please try again.',

        // Laporan Rekap Unit Pengolah
        'laporan.rekapUnit.title': 'Archive Recap Report per Processing Unit',
        'laporan.rekapUnit.breadcrumb': 'Recap per Processing Unit',
        'laporan.rekapUnit.description': 'Generate archive statistics report by processing unit',
        'laporan.rekapUnit.processingUnits': 'Processing Units',
        'laporan.rekapUnit.archivePerUnit': 'Archive',
        'laporan.rekapUnit.perUnit': 'Per Unit',
        'laporan.rekapUnit.statistics': 'Statistics',
        'laporan.rekapUnit.complete': 'Complete',
        'laporan.rekapUnit.proportion': 'Proportion',
        'laporan.rekapUnit.visual': 'Visual',
        'laporan.rekapUnit.aboutDescription': 'This report provides archive statistics summary for each processing unit:',
        'laporan.rekapUnit.archiveCount': 'Archive Count:',
        'laporan.rekapUnit.archiveCountDesc': 'Total unit archives owned by each processing unit',
        'laporan.rekapUnit.fileCount': 'File Count:',
        'laporan.rekapUnit.fileCountDesc': 'Total archive files owned by each processing unit',
        'laporan.rekapUnit.verificationStatus': 'Verification Status:',
        'laporan.rekapUnit.verificationStatusDesc': 'Archive breakdown by status (Pending, Accepted, Rejected)',
        'laporan.rekapUnit.proportionInfo': 'Proportion:',
        'laporan.rekapUnit.proportionInfoDesc': 'Visualization of each unit\'s contribution percentage to total archives',
        'laporan.rekapUnit.displayedInfo': 'Information Displayed:',
        'laporan.rekapUnit.overallSummary': 'Overall summary (total units, archives, files, average)',
        'laporan.rekapUnit.recapTable': 'Recap table per processing unit with verification status',
        'laporan.rekapUnit.barChart': 'Proportion visualization in bar chart form',
        'laporan.rekapUnit.verificationSummary': 'Overall verification status summary',
        'laporan.rekapUnit.unitList': 'Processing Unit List',
        'laporan.rekapUnit.generateReport': 'Generate Report',
        'laporan.rekapUnit.tips': 'Tips:',
        'laporan.rekapUnit.tipsDesc': 'Report will display recap of all processing units. Use date filter to limit data period.',
        'laporan.rekapUnit.fromDate': 'From Date',
        'laporan.rekapUnit.leaveEmptyFrom': 'Leave empty to get all data',
        'laporan.rekapUnit.toDate': 'To Date',
        'laporan.rekapUnit.leaveEmptyTo': 'Leave empty to get data until today',
    },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>(() => {
        const stored = localStorage.getItem('language');
        return (stored === 'id' || stored === 'en') ? stored : 'id';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
    };

    const t = (key: string): string => {
        const dict = translations[language] as Record<string, string>;
        return dict[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
}
